# Generated by Django 6.1.1 on 2026-10-04 10:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название Категории', max_length=50, unique=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, help_text='Автоматически заполняется из названия', verbose_name='URL-идентификатор')),
                ('description', models.TextField(help_text='Описание Категории', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Введите название Продукта', max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(help_text='Описание Продукта', verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото продукта', null=True, upload_to='catalog/photo', verbose_name='Фотография')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Введите цену', max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['price', 'name'],
            },
        ),
    ]
